# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_add_biases <- function(m, v) {
    .Call('mistnet2_rcpp_add_biases', PACKAGE = 'mistnet2', m, v)
}

ifelse_matrix <- function(m, yes, no) {
    .Call('mistnet2_ifelse_matrix', PACKAGE = 'mistnet2', m, yes, no)
}

matrixMultiplyGrad <- function(n_out, error_grad, input_act) {
    .Call('mistnet2_matrixMultiplyGrad', PACKAGE = 'mistnet2', n_out, error_grad, input_act)
}

